### ISSUE TITLE
Três dúvidas para me situar (sobre Contribution, Organização e Dúvidas)

### ISSUE THREAD

**Issue by cahmtoledo** [infobayes/ScientificComputingNewApproach#6]
Vou direto ao ponto:
1)No texto Contribution Guidelines você recomenda que nós criemos um clone no nosso computador local. Isso vai de encontro a algo que o professor RV falou na primeira aula que as tarefas desse curso possam ser inteira hospedadas na nuvem. Com base nisso é absolutamente necessário criar uma cópia no nosso pc ou tem alguma forma de mexer direto do github na web.
2)Sobre arquivos. Eu escrevi um arquivo .tex com um exercício e não sei se eu devo fazer uma modificação do .tex do capítulo de probabilidade e depois subir essa modificação ou subir o meu arquivo (talvez em uma pasta chamada exercícios de probabilidade). E nesse segundo caso depois colocaremos no livro (provavelmente de uma forma espera)
3)Eu não sei se dúvidas devem ser postadas como issues, se temos um fórum para isso ou devo mandar por e-mail queria saber qual o melhor jeito de fazer isso

**Comment by otaviocv** [comment]
Olá @cahmtoledo,

Sobre a primeira questão. É necessário realizar a cópia do repositório local para se trabalhar no projeto, mas após a mudanças serem feitas e enviadas para o Github não há a necessidade de se possuir a cópia local. Sei que a há possibilidade de fazer uma sincronização com o Overleaf, serviço de edição de projetos LaTeX, mas tenho que olhar com detalhes como fazer essa integração.

Sobre a segunda questão. A ideia é que vocês contribuam direto com o livro, não tenha receio de editar os arquivos do livro. Faça todas as modificações que achar necessário e submeta o Pull Request, qualquer mudança que tenha que ser feita ou revisada acontecerá no processo de revisão. O Git é esperto e sabe como juntar os arquivos e decidir se há conflitos entre as versões.

Se você já fez as suas mudanças, coloque-as ao capítulo de probabilidade e verificar se há a necessidade de alguma alteração.

Sobre o terceiro tópico. Por fa

**Comment by cahmtoledo** [comment]
Nossa, ajudou muito. 
Fico feliz em saber que só preciso criar a cópia na hora da alteração.
Sim, você solucionou todas as dúvidas. Pode fechar a issue

**Comment by cahmtoledo** [comment]
Nossa, ajudou muito. 
Fico feliz em saber que só preciso criar a cópia na hora da alteração.
Sim, você solucionou todas as dúvidas. Pode fechar a issue
