### ISSUE TITLE
Probability: Class notes

### ISSUE THREAD

**Issue by GHSAguiar** [infobayes/ScientificComputingNewApproach#9]
Gostaria de tentar trabalhar no registro das formulações em probabilidade, podendo atualizar o conteúdo a cada duas aulas.

Grato desde já pela atenção,

Gabriel

**Comment by otaviocv** [comment]
Gabriel, as contribuições devem ser direcionadas para um tópico específico, seja o contúdo de uma aula específica ou alguma seção em particular. Da forma que você pediu você toma autoria de todas as contribuições em probabilidade, retirando espaço de outras pessoas perticiparem também. 

Vou encerrar essa issue. Se você tiver alguma ideia em particular em mente por favor reabra a issue com as suas propostas.

**Comment by GHSAguiar** [comment]
Então, Otavio... na realidade, o Renato permitiu que algumas pessoas
ficassem trabalhando em notas de aula, mesmo que seja exatamente o mesmo
trabalho para cada uma delas. Desta forma, a issue estaria aberta a quem
quisesse trabalhar com isso. Acho uma boa conversar com o Renato para
deixar isso acertado.
-- 
Gabriel Aguiar

**Comment by otaviocv** [comment]
Vou conversar com o @renatovicente. Mas ainda acho que deveriamos manter dessa forma. Assim poderemos ir adicionando continuamente contribuições ao livro. De qualquer forma, idenpendente da forma quais são suas propostas para adições ao capítulo?

**Comment by GHSAguiar** [comment]
Elaborei um texto contendo as formulações matemáticas em Probabilidade,
apresentadas nas últimas duas aulas. Inclusive, não consegui permissão para
o pull no diretório. Como devo proceder?
-- 
Gabriel Aguiar

**Comment by otaviocv** [comment]
Eu não exatamente o que aconteceu na primeira aula de probabilidade, sobre o que exatamente você escreveu?

Sobre o pull request por favor leia as instruções no documento `CONTRIBUTION.md`.

**Comment by GHSAguiar** [comment]
As primeiras aulas consistiram em definir epaço amostral, sigma-álgebra e
probabilidade, bem como suas propriedades. Alguns teoremas também foram
enunciados.

Li as instruções, mas o tópico 7 já não funcionou: "Push your changes back
to your github fork". O comando $ git push origin probability-class-notes
gera acesso negado.


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by otaviocv** [comment]
Você esta enviando as mudancas para o repositorio original, voce precisa enviar para o seu fork. Certifique-se o clone tenha sido feito do seu fork e nao do repositorio original.

Voce, entao, ira falar sobre:

- Espaco amostral
- Sigma Algebra
- Probabilidade

Voce pretende falar sobre todos os teoremas?
Quais voce ira adicionar?

**Comment by GHSAguiar** [comment]
Certo, Otávio. Vou checar se estou atuando sobre meu fork.

Irei falar sobre o Teorema de Bayes e o Teorema da Probabilidade Total.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by otaviocv** [comment]
Ok. Vou dar _assign_ dessa issue para voce, quando encerrar e abrir o pull request faca referencia a essa issue no PR e a referencia do PR aqui.

**Comment by GHSAguiar** [comment]
Perfeito, Otávio. Obrigado!
-- 
Gabriel Aguiar

**Comment by GHSAguiar** [comment]
The pull request was accomplished. #14
